print('to use this library, your code should look something like this:')
print()
print('import Simu')
print("Simu.simu = 'a'")
print("#simulation options are 'a_old', 'a', 'b' and 'c'")
print('import he_solver')
print('a = he_solver.he_solver(1,0.5,10)')
print('# he_solver parameters are (T,lambda,N), be aware that if you are going to execute implicit methods, your lambda will be over writen')
print('a.execute_euler()')
print('#your options are a.execute_euler, a.execute_implict_euler, a.execute_crank_nicolson')
print('#all charts should appear inside a folder called /Data/')
print('to see all the pre-existing data go to this directory and explore the files, names are self-explicative')
import inspect, os
print(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))))
print()